### 学习实验室🧪成为transformers大师

In [1]:
import torch
# 示例数据
attention_mask = torch.tensor([[1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0],
                               [1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0]])
inputs_embeds = torch.rand((2, 29, 2048))  # 假设每个 token 有 2048 维度的 embedding

In [12]:
torch.unbind(attention_mask, dim=0)[0].unsqueeze(0).shape

torch.Size([1, 29])

In [6]:
test_mask = (attention_mask == 1)
test_mask

tensor([[ True,  True,  True,  True, False, False,  True,  True, False,  True,
         False,  True, False,  True,  True, False,  True,  True,  True, False,
          True,  True,  True, False, False,  True,  True, False, False],
        [ True,  True,  True,  True, False, False,  True,  True, False,  True,
         False,  True, False,  True,  True, False,  True,  True,  True, False,
          True,  True,  True, False, False,  True,  True,  True, False]])

In [10]:
attention_mask[test_mask]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [2]:
attention_mask

tensor([[1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
         0, 1, 1, 0, 0],
        [1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
         0, 1, 1, 1, 0]])

In [3]:
inputs_embeds, inputs_embeds.shape

(tensor([[[0.1256, 0.2637, 0.8350,  ..., 0.3745, 0.7387, 0.1357],
          [0.2252, 0.8413, 0.8065,  ..., 0.9840, 0.8412, 0.4433],
          [0.9412, 0.0750, 0.2897,  ..., 0.2907, 0.2094, 0.0654],
          ...,
          [0.9306, 0.2807, 0.4559,  ..., 0.2984, 0.7688, 0.1653],
          [0.1689, 0.0974, 0.5173,  ..., 0.4540, 0.1680, 0.6150],
          [0.5390, 0.5713, 0.9806,  ..., 0.9417, 0.2553, 0.2869]],
 
         [[0.5117, 0.1795, 0.1624,  ..., 0.2033, 0.1645, 0.6800],
          [0.7631, 0.1600, 0.6009,  ..., 0.8479, 0.9125, 0.6817],
          [0.0312, 0.7664, 0.9006,  ..., 0.4601, 0.9618, 0.9685],
          ...,
          [0.9338, 0.9738, 0.0825,  ..., 0.1861, 0.1905, 0.8730],
          [0.7380, 0.5967, 0.8574,  ..., 0.0567, 0.2606, 0.7162],
          [0.6256, 0.3214, 0.4696,  ..., 0.5606, 0.6839, 0.4260]]]),
 torch.Size([2, 29, 2048]))

In [4]:
# 扩展 attention_mask 的维度，变成 [batch, seq_len, 1]
attention_mask_expanded = attention_mask.unsqueeze(-1)  # [1, 29, 1]

# 将 attention_mask 应用到 inputs_embeds 中，将无效的 token 的嵌入置为零
masked_inputs = inputs_embeds * attention_mask_expanded  # [1, 29, 2048]

In [9]:
masked_inputs.shape, masked_inputs

(torch.Size([2, 29, 2048]),
 tensor([[[0.1256, 0.2637, 0.8350,  ..., 0.3745, 0.7387, 0.1357],
          [0.2252, 0.8413, 0.8065,  ..., 0.9840, 0.8412, 0.4433],
          [0.9412, 0.0750, 0.2897,  ..., 0.2907, 0.2094, 0.0654],
          ...,
          [0.9306, 0.2807, 0.4559,  ..., 0.2984, 0.7688, 0.1653],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
 
         [[0.5117, 0.1795, 0.1624,  ..., 0.2033, 0.1645, 0.6800],
          [0.7631, 0.1600, 0.6009,  ..., 0.8479, 0.9125, 0.6817],
          [0.0312, 0.7664, 0.9006,  ..., 0.4601, 0.9618, 0.9685],
          ...,
          [0.9338, 0.9738, 0.0825,  ..., 0.1861, 0.1905, 0.8730],
          [0.7380, 0.5967, 0.8574,  ..., 0.0567, 0.2606, 0.7162],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]]))

In [5]:
masked_inputs, attention_mask_expanded, attention_mask_expanded.shape

(tensor([[[9.0241e-01, 9.6770e-01, 1.3671e-01,  ..., 1.2862e-01,
           5.4522e-01, 3.9150e-01],
          [1.9857e-01, 5.4013e-01, 1.3473e-01,  ..., 6.9671e-01,
           6.4195e-01, 6.3824e-01],
          [7.6589e-01, 6.6113e-01, 2.7364e-01,  ..., 6.5409e-01,
           4.5100e-01, 2.2926e-01],
          ...,
          [7.1471e-01, 1.1053e-01, 5.7027e-01,  ..., 5.1748e-01,
           6.0426e-01, 5.7054e-01],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],
 
         [[2.1980e-01, 2.6393e-01, 8.6041e-01,  ..., 1.8984e-04,
           6.4444e-01, 4.8646e-01],
          [9.1924e-01, 8.7242e-02, 5.3079e-01,  ..., 1.9471e-01,
           9.6642e-01, 7.8220e-01],
          [6.3319e-02, 3.7353e-01, 6.7665e-01,  ..., 5.3962e-03,
           2.2609e-01, 5.9758e-01],
          ...,
          [6.8072e-01, 1.2033e-01, 9.7152e-01,  ..., 8.106

In [2]:
import json
data_path = "/home/lsy/workspace/papercode/LLaVA/playground/data/eval/scienceqa/llava_test_CQM-A.json"
list_data_dict = json.load(open(data_path, "r"))
list_data_dict, len(list_data_dict)

([{'id': '4',
   'conversations': [{'from': 'human',
     'value': 'Which figure of speech is used in this text?\nSing, O goddess, the anger of Achilles son of Peleus, that brought countless ills upon the Achaeans.\n—Homer, The Iliad\nA. chiasmus\nB. apostrophe'},
    {'from': 'gpt', 'value': 'B'}]},
  {'id': '5',
   'image': '5/image.png',
   'conversations': [{'from': 'human',
     'value': "<image>\nContext: People can use the engineering-design process to develop solutions to problems. One step in the process is testing if a potential solution meets the requirements of the design.\nThe passage below describes how the engineering-design process was used to test a solution to a problem. Read the passage. Then answer the question below.\n\nGordon was an aerospace engineer who was developing a parachute for a spacecraft that would land on Mars. He needed to add a vent at the center of the parachute so the spacecraft would land smoothly. However, the spacecraft would have to travel at a

In [5]:
sources = list_data_dict[1]
sources = [sources]
import copy
copy.deepcopy([e["conversations"] for e in sources]), sources
# sources['conversations'][0]['value'].split('<image>')

['sh', 'yulu']

In [1]:
import json
predictions = [json.loads(line) for line in open('/home/lsy/workspace/papercode/LLaVA/playground/data/eval/scienceqa/answers/llava-noaligned-qwen3BInstruct-clipvL14.jsonl')]
predictions = {pred['question_id']: pred for pred in predictions}

In [2]:
predictions

{'4': {'question_id': '4',
  'prompt': "Which figure of speech is used in this text?\nSing, O goddess, the anger of Achilles son of Peleus, that brought countless ills upon the Achaeans.\n—Homer, The Iliad\nA. chiasmus\nB. apostrophe\nAnswer with the option's letter from the given choices directly.",
  'text': 'B',
  'answer_id': 'iJfwxRheZ7edb4giwUCzH8',
  'model_id': 'model001',
  'metadata': {}},
 '5': {'question_id': '5',
  'prompt': "<image>\nContext: People can use the engineering-design process to develop solutions to problems. One step in the process is testing if a potential solution meets the requirements of the design.\nThe passage below describes how the engineering-design process was used to test a solution to a problem. Read the passage. Then answer the question below.\n\nGordon was an aerospace engineer who was developing a parachute for a spacecraft that would land on Mars. He needed to add a vent at the center of the parachute so the spacecraft would land smoothly. How

In [3]:
modify_text = []
for qid, pred in predictions.items():
    modify_text.append(pred['text'].split('assistant\n')[-1].strip())

In [ ]:
import json, os
split = 'train'
base_dir = '/home/lsy/workspace/papercode/ScienceQA/data/scienceqa'
split_indices = json.load(open(os.path.join(base_dir, "pid_splits.json")))[split]
split_indices

In [21]:
import torch
# 示例数据
attention_mask = torch.tensor([[1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0],
                               [1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0]]).bool()
inputs_tokens = torch.rand((2, 29))  # 假设每个 token 有 2048 维度的 embedding
inputs_tokens, attention_mask

(tensor([[0.7084, 0.7627, 0.2144, 0.8268, 0.2582, 0.4404, 0.6423, 0.4317, 0.9175,
          0.6191, 0.1455, 0.1128, 0.9176, 0.2264, 0.8312, 0.5631, 0.1913, 0.0454,
          0.4795, 0.1094, 0.4216, 0.3278, 0.4719, 0.0891, 0.4680, 0.2047, 0.6219,
          0.8366, 0.5797],
         [0.1606, 0.4111, 0.2588, 0.0452, 0.9424, 0.2527, 0.5810, 0.0625, 0.8899,
          0.3123, 0.9823, 0.8010, 0.8349, 0.6035, 0.5362, 0.8581, 0.2741, 0.1858,
          0.7290, 0.6346, 0.9818, 0.8855, 0.3177, 0.4359, 0.7174, 0.9783, 0.4692,
          0.1904, 0.3901]]),
 tensor([[ True,  True,  True,  True, False, False,  True,  True, False,  True,
          False,  True, False,  True,  True, False,  True,  True,  True, False,
           True,  True,  True, False, False,  True,  True, False, False],
         [ True,  True,  True,  True, False, False,  True,  True, False,  True,
          False,  True, False,  True,  True, False,  True,  True,  True, False,
           True,  True,  True, False, False,  True,  True,

In [25]:
for mask in attention_mask:
    print(mask)

tensor([ True,  True,  True,  True, False, False,  True,  True, False,  True,
        False,  True, False,  True,  True, False,  True,  True,  True, False,
         True,  True,  True, False, False,  True,  True, False, False])
tensor([ True,  True,  True,  True, False, False,  True,  True, False,  True,
        False,  True, False,  True,  True, False,  True,  True,  True, False,
         True,  True,  True, False, False,  True,  True,  True, False])


In [28]:
undermask_inputs = [inputs[mask].unsqueeze(0) for inputs, mask in zip(inputs_tokens, attention_mask)]
undermask_inputs[0], undermask_inputs[1], undermask_inputs[0].shape, undermask_inputs[1].shape
# undermask_inputs[0] = torch.cat([undermask_inputs[0], ])
# undermask_inputs = torch.stack(undermask_inputs)

(tensor([[0.7084, 0.7627, 0.2144, 0.8268, 0.6423, 0.4317, 0.6191, 0.1128, 0.2264,
          0.8312, 0.1913, 0.0454, 0.4795, 0.4216, 0.3278, 0.4719, 0.2047, 0.6219]]),
 tensor([[0.1606, 0.4111, 0.2588, 0.0452, 0.5810, 0.0625, 0.3123, 0.8010, 0.6035,
          0.5362, 0.2741, 0.1858, 0.7290, 0.9818, 0.8855, 0.3177, 0.9783, 0.4692,
          0.1904]]),
 torch.Size([1, 18]),
 torch.Size([1, 19]))

In [9]:
import torch

# 示例数据
batch_size, seq_len, embed_dim = 2, 29, 2048
inputs_embeds = torch.rand((batch_size, seq_len, embed_dim))  # 模拟嵌入
attention_mask = torch.randint(0, 2, (batch_size, seq_len))  # 0表示padding，1表示有效token

# 将 attention_mask 扩展为 (bs, seq_len, 1) 形状，作为布尔掩码
mask_expanded = attention_mask.bool()

# 过滤 padding token 的嵌入
masked_inputs = [embeds[mask] for embeds, mask in zip(inputs_embeds, mask_expanded)]

# 计算每个 batch 过滤后的嵌入均值
masked_mean_embeds = torch.stack([emb.mean(dim=0) if emb.numel() > 0 else torch.zeros(embed_dim) for emb in masked_inputs])

# 打印形状，应该是 (bs, embed_dim)
print(masked_mean_embeds.shape)  # 期望输出: (2, 2048)

torch.Size([2, 2048])


In [11]:
masked_inputs[0].shape, masked_inputs[0]

(torch.Size([10, 2048]),
 tensor([[2.6902e-01, 6.4559e-01, 9.0086e-01,  ..., 4.5112e-01, 2.6390e-01,
          8.9943e-05],
         [1.9875e-01, 5.0195e-01, 3.7270e-01,  ..., 2.6246e-02, 1.3392e-01,
          6.7156e-01],
         [6.9916e-01, 3.0498e-01, 2.1617e-02,  ..., 2.0773e-01, 2.1089e-01,
          5.0061e-02],
         ...,
         [7.0023e-01, 7.3769e-01, 8.5558e-01,  ..., 9.7707e-01, 5.5567e-01,
          7.5160e-01],
         [1.4878e-01, 3.8820e-01, 2.6015e-01,  ..., 8.2811e-02, 7.7301e-01,
          5.5666e-01],
         [4.4431e-02, 9.3003e-01, 4.1777e-01,  ..., 8.2066e-01, 1.1349e-01,
          5.3491e-01]]))

In [34]:
mm = [mask for embeds, mask in zip(inputs_embeds, mask_expanded)]
mm

[tensor([False, False,  True,  True,  True,  True,  True, False,  True,  True,
          True, False,  True,  True,  True, False, False,  True, False, False,
          True,  True, False, False,  True, False,  True,  True,  True]),
 tensor([ True,  True,  True,  True, False, False, False,  True, False,  True,
         False, False, False, False,  True, False, False,  True,  True, False,
         False, False,  True, False,  True,  True, False,  True, False])]

In [38]:
print(inputs_embeds)
print(masked_inputs[0].mean(dim=0).shape)
inputs_embeds[0][27], masked_inputs[0].shape, masked_inputs[1].shape

tensor([[[0.4791, 0.5596, 0.4211,  ..., 0.5557, 0.4878, 0.6292],
         [0.0489, 0.1847, 0.1481,  ..., 0.3033, 0.5652, 0.2276],
         [0.6251, 0.0026, 0.0870,  ..., 0.1309, 0.4974, 0.9215],
         ...,
         [0.2057, 0.7651, 0.9952,  ..., 0.1867, 0.4657, 0.5609],
         [0.3159, 0.7301, 0.7453,  ..., 0.4040, 0.7243, 0.8049],
         [0.9708, 0.4392, 0.1264,  ..., 0.8528, 0.3923, 0.6216]],

        [[0.5234, 0.4297, 0.9020,  ..., 0.9952, 0.0056, 0.3628],
         [0.9674, 0.3667, 0.9782,  ..., 0.6472, 0.1277, 0.9078],
         [0.7561, 0.5068, 0.8979,  ..., 0.2537, 0.5760, 0.8008],
         ...,
         [0.1098, 0.7754, 0.1118,  ..., 0.5161, 0.9860, 0.7436],
         [0.2289, 0.3846, 0.2352,  ..., 0.8628, 0.2644, 0.1926],
         [0.0910, 0.4473, 0.7900,  ..., 0.9624, 0.1668, 0.1763]]])
torch.Size([2048])


(tensor([0.3159, 0.7301, 0.7453,  ..., 0.4040, 0.7243, 0.8049]),
 torch.Size([18, 2048]),
 torch.Size([13, 2048]))

In [35]:
attention_mask

tensor([[0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
         1, 0, 1, 1, 1],
        [1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
         1, 1, 0, 1, 0]])